### ISSUE TITLE
Pass the input variables via context

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#11]
AT:
* I can pass the input variables as a context instead of a `Map[String, Any]`
* Use Case: lazy loading, more flexibility to provide the variables

```
trait VariableContext {
  def apply(key: String): Option[Any]
}

class FeelEngine(...) {

  def evalExpression(expression: String, context: VariableContext): EvalResult = {
    eval(FeelParser.parseExpression, expression, context)
  }
```

**Comment by hannes-o-brunner** [comment]
This would definitely be good, and it should also be supported for custom contexts that can be generated by a custom value mapper (e.g. ValContext)

**Comment by saig0** [comment]
@hannes-o-brunner , what do you mean with 

> supported for custom contexts that can be generated by a custom value mapper

?

Can you provide an example, please.

**Comment by hannes-o-brunner** [comment]
To efficiently support (possibly deeply) nested domain models and/or entities with many attributes.
Assume we have a ruleset that calculates some kind of fee for a holding in a given financial product for a given client. Some rules might depend on aspects of the client, others on aspects of the product.
So in one rule you could have something like `holding.portfolio.owner.domicileAddress.country.vatCode` while in another rule you can have something like `holding.product.issuer.category.feeCalculation.baseRate`.
The hit ratio for context element `holding` is close to 100%, but I would like to avoid having to enumerate all the attributes of all the nested entities at this time and rather do it lazily, only if required (some entities above can easily go to 50+ attributes).
I assume if we would already have the proposed functionality to fill context elements on demand, this could also be re-used for nested entities / contexts?

**Comment by hannes-o-brunner** [comment]
@saig0 btw as an example see the testcase for the custom value mapper in [CustomValueMapperTest](https://github.com/camunda/feel-scala/pull/12/files#diff-47e241c4517b303df948377f33971f3b), `toVal` for `Enumeration` and `DomainObject`

**Comment by saig0** [comment]
@hannes-o-brunner , thank you for the details! 

As always, do you want to provide a PR?

**Comment by hannes-o-brunner** [comment]
@saig0 OK, I will look into this.

What is your idea regarding FeelEngine API:
- do you want to duplicate the three external methods
- should we add an additional variableContext to each of them (where we look into the variable context only if the Map is empty)
- should we create a context class hierarchy (Context <- FixedContext, VariableContext)?

**Comment by hannes-o-brunner** [comment]
I would lean towards the second variant, an additional dynamic context with "empty" default.

Ah, and naming: DynamicContext vs VariableContext?

**Comment by saig0** [comment]
I would prefer additional methods because it makes the api easy to use. However, you can transform the map into a variable context internally.

``` 
def evalExpression(expression: String, context: Map[String, Any] = Map())

def evalExpression(expression: String, context: VariableContext)
```

**Comment by hannes-o-brunner** [comment]
@saig0 finally found the time to do the [PR](https://github.com/camunda/feel-scala/pull/14)

**Comment by hannes-o-brunner** [comment]
@saig0 BTW, instead of the current implementation I probably would have changed `Context` to a mutable one, but since I don't know how you feel about this I did not do it.

So every time a `key` is not found in `variables: mutable.Map`, it would be looked up with `variableProvider` and stored in `variables` again (memoizing `variableProvider`). This would then likely have to change signatures of ++ and + (returning Unit instead a new Context). Constructor and method arguments could be left immutable, in order not to break exisiting consumers.

**Comment by saig0** [comment]
@hannes-o-brunner , thank you for your PR. I try to have a look into it in the next days.

**Comment by saig0** [comment]
@hannes-o-brunner , your PR looks good. I made a small change and created a trait + objects for the variable provider to make the api a bit easier/smaller (see 45929c0). 

Only one thing, currently I'm not sure about the `ValVariableContext`. In your example `ValueMapper` (in class `CustomValueMapperTest.scala`), you need to read the properties and values every time when you make a look up. 
As an alternative, I'm thinking about a `LazyVal` which works similar to Scala's `lazy`. When the `ValueMapper` map a domain object (i.e. a complex object) then it creates a map from `String` to `LazyVal`. The value of `LazyVal` is evaluated while the first lookup for the key. What do you think of it?

Regarding a mutable context, I don't think it's a good idea because you need different scopes while evaluation. Using a mutable scope, you may expose variables to outer scopes.

**Comment by hannes-o-brunner** [comment]
@saig0 not sure if I completely follow you, but what you are describing more or less corresponds to the idea with the mutable context, only that you implement it in the `ValueMapper` instead of the `Context`?

Of course I am not as deep in the code as you are, but I somehow have the feeling that going this route you kind of mix the semantics of the `ValueMapper` (mapping "simple" values, context free and stateless) and the `Context` (providing key-value pairs)?

**Comment by hannes-o-brunner** [comment]
@saig0 just re-read your comment, the idea of the mutable context of course is not to have 1 "global" context, but one mutable / lazily evaluated context per "covered" entity, which lazily collects accessed fields, very much like your proposal

**Comment by saig0** [comment]
@hannes-o-brunner , thank's for clarification. Do you mean that you want to hold the values from `ValVariableContext` somewhere (not globally) to avoid mutable lookups?

In this case, I agree with you. But I think we should not hold the values in the 'global' variable context. Maybe, we could build something in `ValVariableContext` itself. 
Btw, I think we can combine `ValVariableContext` and `ValContext` because they behave similar from outside.

```
case class ValContext(e: List[(String, Val)], lookup: (String) => Option[Val] = (_ => None)) extends Val {

  val entries = scala.collection.mutable.Map[String, Val]() ++ e.toMap

  def apply(key: String): Option[Val] = entries.get(key) match {
    case Some(value)  => Some(value)
    case None         => lookup(key) match {
      case None         => None
      case Some(value)  => {
        entries += key -> value
        Some(value)
      }
    }
  }
}
```

Do you have an idea how to use this concept in the `DefaultValueMapper#useObjectAsContext`?  
I would like to avoid the lookup for fields and method names every time.

**Comment by saig0** [comment]
@hannes-o-brunner , I merged the current changes to master. Please have a look at it. Do you want to change anything? What about the value cache of the `ValVariableContext`?

**Comment by hannes-o-brunner** [comment]
Hi @saig0 Philipp, sorry for the silence, I was on a looong summer break :-)

I would have suggested to refactor the code such that we extract the common functionality out of `Context/ValContext/ValVariableContext` into one common base trait/class. This common base would +/-
 be what `Context` is now plus memoizing dynamically provided variables into the `variables` Map.

This of course would incur some refactoring, most probably straightforward, except line 28 in FeelInterpreter which might take 5 minutes to think it over :-)

`case ConstContext((k,v) :: entries) => ValContext( entries.foldLeft( evalContextEntry(k,v) ){ (ctx, entry) => ctx ++ evalContextEntry(entry._1, entry._2)(context ++ ctx.toMap) } )`

If you would agree to the refactoring, I would do a corresponding PR.

**Comment by hannes-o-brunner** [comment]
Just realised I was looking at an older version of `Context`, the refactor would then re-introduce something like `variableProvider` in the base class again.

**Comment by saig0** [comment]
Welcome back @hannes-o-brunner :)

I'm looking forward to your PR. We can discuss the details better at the code.

One comment to FeelInterpreter#line-28: when we create a context then we must include the previous entries of the context for the evaluation because they can depend on each other. E.g.: 
```
{
    a: 2
    b: a * 4
}
```

**Comment by hannes-o-brunner** [comment]
@saig0
Hallo Philipp

Ich hab jetzt mal eine [erste Version](https://github.com/hannes-o-brunner/feel-scala/commit/5992ba52defb4b30c8ac59724eab659c4eaa3399) in meinem Fork Repo erstellt.
Es ist noch nicht alles optimiert, speziell das Memoising fehlt noch, aber ich denke wir sollten uns zuerst einigen ob die Stossrichtung stimmt, dann können wir den Rest noch optimieren.

Die Idee ist dass der Context generalisiert wird (liefert `variable`s und `function`s) und es dann je nach Anwendungszweck unterschiedliche Implementation gibt (Default, Object, Custom, ...).

`VariableProvider` gibt es nicht mehr, bei Bedarf kann ja direkt ein Custom Context erstellt werden.
Dadurch ändert zwar das Public API, aber ich vermute Du hast noch nicht viele externe Konsumenten?

Was man auch noch schöner machen könnte ist die Gleichbehandlung von allen Funktionen, aktuell unterscheiden sich BuiltIns und Custom, letztere sind ja unter Variables gespeichert und generieren etwas andere Fehlermeldungen falls etwas nicht klappt.

Einige Listen sind durch Maps erstetzt, macht m.E. mehr Sinn.

Gruss
Hannes

**Comment by saig0** [comment]
@hannes-o-brunner , you did a great job :+1:   I like your changes and I think they go in the right direction.

Puplic api is no problem in this case. You only have to ensure that the factory + plugin modules still work.

Similar behavior of custom and built-in function would be good too. 

Best regards 

(Ich würde die Konversation gern in Englisch fortführen, damit jeder es verstehen kann. Danke ;) )

**Comment by hannes-o-brunner** [comment]
@saig0 
Hi Philipp
How do you run your build/tests on the whole package?
If I run the top-level pom with maven, it does not find any tests (presumably since they are scala tests), if I run `sbt test` in the individual sub-projects, in -factory and -plugin it does not find the scala-feel dependencies.
Best
Hannes

**Comment by saig0** [comment]
@hannes-o-brunner , you're right. I didn't realized that Maven ignored the tests :sweat_smile:   
I created an issue #22 for that. Feel free to fix it.   
For now, you must run the tests for all modules.

**Comment by hannes-o-brunner** [comment]
@saig0 
While the factory tests work, the plugin test crashes on my machine (without any changes from my side).
Before I spend too much time hunting it down, does this work for you?
I get the following when running `sbt test` in the plugin subproject:

`
[info] CamundaFeelEnginePluginTest:
[info] A Camunda engine with FEEL Scala plugin
[info] - should has FEEL Scala Factory
[info] - should set default expression languages
[info] Exception encountered when attempting to run a suite with class name: org.camunda.feel.CamundaFeelEnginePluginTest *** ABORTED ***
[info]   org.camunda.bpm.engine.ProcessEngineException: ENGINE-03017 Could not perform operation 'drop' on database schema for SQL Statement: 'alter table ACT_RE_DECISION_DEF
[info] drop constraint ACT_FK_DEC_REQ'.
[info]   at org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.performDatabaseOperationException(EnginePersistenceLogger.java:221)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:668)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:595)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeMandatorySchemaResource(DbSqlSession.java:407)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.dbSchemaDropDmn(DbSqlSession.java:398)
[info]   at org.camunda.bpm.engine.impl.db.AbstractPersistenceSession.dbSchemaDrop(AbstractPersistenceSession.java:136)
[info]   at org.camunda.bpm.engine.impl.SchemaOperationProcessEngineClose.execute(SchemaOperationProcessEngineClose.java:29)
[info]   at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
[info]   at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:104)
[info]   at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:66)
[info]   ...
[info]   Cause: org.h2.jdbc.JdbcSQLException: Tabelle "ACT_RE_DECISION_DEF" nicht gefunden
[info] Table "ACT_RE_DECISION_DEF" not found; SQL statement:
[info] alter table ACT_RE_DECISION_DEF
[info] drop constraint ACT_FK_DEC_REQ [42102-193]
[info]   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[info]   at org.h2.message.DbException.get(DbException.java:179)
[info]   at org.h2.message.DbException.get(DbException.java:155)
[info]   at org.h2.command.Parser.tableIfTableExists(Parser.java:5673)
[info]   at org.h2.command.Parser.commandIfTableExists(Parser.java:5686)
[info]   at org.h2.command.Parser.parseAlterTable(Parser.java:5511)
[info]   at org.h2.command.Parser.parseAlter(Parser.java:4844)
[info]   at org.h2.command.Parser.parsePrepared(Parser.java:344)
[info]   at org.h2.command.Parser.parse(Parser.java:317)
[info]   at org.h2.command.Parser.parse(Parser.java:289)
[info]   ...
Okt 02, 2017 10:16:43 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [mixed-dmn-config.cfg.xml]
[info] CamundaFunctionProviderTest:
[info] The function 'now()'
[info] - should return the current date-time *** FAILED ***
[info]   Mon Oct 02 10:16:44 CEST 2017 was not an instance of java.time.LocalDateTime, but an instance of java.util.Date (CamundaFunctionProviderTest.scala:43)
[info] The function 'currentUser()'
[info] - should return the current user id
[info] - should return null if no user is authenticated
[info] The function 'currentUserGoups()'
[info] - should return list of current group ids
[info] - should return null if no group is authenticated
Okt 02, 2017 10:16:44 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [override-dmn-config.cfg.xml]
[info] CamundaFeelEnginePluginConfigTest:
[info] A Camunda engine with FEEL Scala plugin
[info] - should set the DMN engine configuration
[info] - should extend an existing DMN engine configuration
[info] - should allow to override the default expression languages
[info] Run completed in 4 seconds, 911 milliseconds.
[info] Total number of tests run: 10
[info] Suites: completed 2, aborted 1
[info] Tests: succeeded 9, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         org.camunda.feel.CamundaFunctionProviderTest
[error] Error during tests:
[error]         org.camunda.feel.CamundaFeelEnginePluginTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 13 s, completed 02.10.2017 10:16:45
`

**Comment by hannes-o-brunner** [comment]
@saig0 
Hi Philipp

Finally submitted a [PR](https://github.com/camunda/feel-scala/pull/24)
I did some additional cleanup, where you might or might not agree :-)

- Refactored the SPI marker interfaces (CustomXY instead of the base traits, I found this a bit unnatural)
- Refactored function handling, as mentioned
- ContextBase does now memoise
- Refactored ObjectContext: should be more efficient as long as not too many different function calls on the same context
- Changed semantics of ObjectContext to only support public API (instead of being able to access private fields with getDeclaredFields, not sure why you would have supported that)
- all tests run again, so hopefully not too much broken

Best
Hannes

**Comment by saig0** [comment]
@hannes-o-brunner , very good :tada: 

I'll merge your PR with small changes in the next days.

Thank you :+1:

**Comment by saig0** [comment]
Merged.
