### ISSUE TITLE
Improve Data Types documentation

### ISSUE THREAD

**Issue by koevskinikola** [camunda/feel-scala#112]
**Is your feature request related to a problem? Please describe.**
With the `Camunda Value Mapper` docs removed, it is not clear how Variables are transformed into FEEL data types and vice versa. 

**Describe the solution you'd like**
The [Data Types](https://camunda.github.io/feel-scala/feel-data-types) documentation page should cover the transformation to-and-from FEEL data types.

Issue is related to #111

**Comment by saig0** [comment]
The [documentation](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-data-types/) mentions the Java type for a given FEEL type. 

I assume that this information is enough for now. Anyone feel free to open this issue again if something important is missing.
