### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#120]
* add documentation for Camunda/Zeebe devs how to release this project (code freeze, release in CI, GitHub release, changelog, etc.)

CI: https://ci.cambpm.camunda.cloud/view/Sideprojects/job/camunda-github-org/job/feel-scala/job/master

**Comment by tasso94** [comment]
We should also document how to create a new version of the documentation in case of a major or minor release (there is no dedicated documentation for patch releases). See #128.

**Comment by saig0** [comment]
The release process is documented in the issue template "New Release". For every release, we can create a new issue of this template and follow the instructions.

@koevskinikola what do you think about this?

**Comment by koevskinikola** [comment]
I just went through the issue template. Looks good, the only thing I wasn't aware of is the GitHub release. 

I just noticed that maybe this should be corrected:
`copy '/docs/develop/' to '/docs/develop/<PREVIOUS_VERSION>' `
into this:
`copy '/docs/develop/' to '/docs/<PREVIOUS_VERSION>/' `

**Comment by saig0** [comment]
Good catch :+1:
I fixed it.
