### ISSUE TITLE
Improve documentation versioning

### ISSUE THREAD

**Issue by koevskinikola** [camunda/feel-scala#130]
**Is your feature request related to a problem? Please describe.**
Currently, the documentation versioning (added with #129) is only visible on the main `index` page and can be seen in the URL of the documentation pages. 

However, it is not immediately obvious to a user what version of a documentation page they are viewing.

**Describe the solution you'd like**
The version of the documentation currently being viewed should be available on every documentation page.

**Comment by saig0** [comment]
We improved the versioning a lot with #218.
