### ISSUE TITLE
odd() function doesn't work for negative numbers

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#151]
**Describe the bug**
The `odd()` function produces a wrong result for negative numbers.

**To Reproduce**
Expression: `odd(-1)` returns `false` but should be `true`.

**Expected behavior**
`odd(-1)` returns `true`

**Environment**
* FEEL engine version: 1.11.2

**Comment by kaaquist** [comment]
@saig0 I can create a fix for this here.
