### ISSUE TITLE
number() function doesn't accept null arguments

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#153]
**Describe the bug**
I can't pass `null` for the optional parameters of the `number()` function.

**To Reproduce**
Expression `number("1000000.01", null, ".")` produces a failure but should return `1000000.01`

**Expected behavior**
``` 
number("1000000.01", null, ".") -> 1000000.01
number("1,000,000", ",", null) -> 1000000
number("1,000,000.00", ",", null) -> 1000000.00
```

**Environment**
* FEEL engine version: 1.11.2

**Comment by kaaquist** [comment]
I can create this here if that is ok?
