### ISSUE TITLE
instance of Any doesn't work

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#157]
**Describe the bug**
I can not check if a value is of type `Any` using `instance of`.

**To Reproduce**
Expression `x instance of Any` fails to evaluate. 

**Expected behavior**
`Any` is the upper type of all other types. The expression `x instance of Any` should always return `true` if `x` is not `null`. 

**Environment**
* FEEL engine version: 1.11.2

**Comment by kaaquist** [comment]
Is this up for grab?

I looked in to this here briefly and it seems that the `x instance of Any` is part of the `FeelInterpreter.scala` class.
https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala#L124

You been so kind to share the DMN specs before, can you point me in the right direction. 
Cheers.

**Comment by kaaquist** [comment]
Should I add `AnyVal` and `AnyRef` too?

**Comment by saig0** [comment]
From the spec:

![image](https://user-images.githubusercontent.com/4305769/95156098-f9f47080-0795-11eb-8420-abc98c6bb780.png)

![image](https://user-images.githubusercontent.com/4305769/95156267-6a02f680-0796-11eb-96c2-650ff11d8267.png)

![image](https://user-images.githubusercontent.com/4305769/95156291-7be49980-0796-11eb-980e-8dc1be6acfe9.png)

![image](https://user-images.githubusercontent.com/4305769/95156490-ff05ef80-0796-11eb-9852-d61be5fd8342.png)
