### ISSUE TITLE
I can access the weekday as property of a date/date-time

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#160]
**Describe the bug**
I can not access the `weekday` property of a date/date-time value. 

**To Reproduce**
Expression `date("2018-12-10").weekday` fails to evaluate but should return `1`.

**Expected behavior**
A date/date-time value has a property `weekday`. The property is a number value `[1..7]` where `1` is Monday and `7` is Sunday.

**Environment**
* FEEL engine version: 1.11.2

**Comment by kaaquist** [comment]
Can I create a fix for this here?
