### ISSUE TITLE
get entries() function returns the entries in a different order

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#161]
**Describe the bug**
The function `get entries()` may return the entries in a different order than they are defined in the context.

**To Reproduce**
Expression `get entries({a: "foo", b: "bar"})`
 returns 
`[{value=bar, key=b}, {value=foo, key=a}]` 
but should be 
`[{value=foo, key=a}, {value=bar, key=b}]`

**Expected behavior**
The function `get entries()` returns the entries in the same order as they are defined in the context.

**Environment**
* FEEL engine version: 1.11.2

**Comment by P3trur0** [comment]
May I take this as well?
