### ISSUE TITLE
abs() function can not be invoked with named parameter "n"

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#164]
**Describe the bug**
The function `abs()` can not be invoked with a named parameter `n`.

With DMN 1.3, the parameter name of the `abs()` function changed from `number` to `n`.

**To Reproduce**
Expression `abs(n: 1)` fails to evaluate but should return `1`

**Expected behavior**
The `abs()` function can be invoked either with a named parameter `n` or `number`.

**Environment**
* FEEL engine version: 1.11.2

**Comment by daniel-shuy** [comment]
I'd like to work on this

**Comment by daniel-shuy** [comment]
Created a PR (#199) to fix this
