### ISSUE TITLE
Can not access property of nested lists

### ISSUE THREAD

**Issue by Firestorm87** [camunda/feel-scala#174]
Hi,

i am using simple list values with expressions like this:
`=testList.get(1).innerValue="a"`

because that is working fine i tried also an expression on nested lists like:
`=testList.get(1).innerList.get(1)="a"`

But that expression is not parseable.
I get the following error:
`Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following errors: 'workflow.bpmn': - Element: Flow_0itig1o > conditionExpression - ERROR: failed to parse expression 'testList.get(1).innerList.get(1)="a"': [1.30] failure: end of input expected testList.get(1).innerList.get(1)="a"`

Is access of nested lists not possible, or how to do such expressions?

**Comment by saig0** [comment]
Hi @Firestorm87,

thank you for reporting. This notation of accessing a list is not recommended. 

In FEEL, a list entry can be accessed by using the following syntax:

```
list[index]
// the index starts by 1 

[1,2,3,4][1] 
// -> 1

[[1,2],[3,4]][1][2]
// -> 2
```

Does this work for you?

**Comment by Firestorm87** [comment]
Hi @saig0 

your expression is working. But it's not a solution for my problem. A multidimensional array with primitive values is working fine.
Also accessing full objects in nested lists is working.
But my problem is to access a property of a complex list-item (JSON-Object).

Working multidimensional
`=[[1,2],[3,4]][1][2]=2`

Working nested list (full object)
`=test[1].test[2]=2`

Error nested list and property access
`=test[1].test[2].value=2`

Access with "get(idx)" and "[idx]" always returns the same value / error.
Do you have any further ideas?

**Comment by saig0** [comment]
Yes. This is a limitation of the parser. You need to add brackets to make it happy:

``` 
(test[1].test[2]).value=2
```

Does this work fo you?

**Comment by Firestorm87** [comment]
Hi @saig0 ,

for my mini example this notation works well.
I will have a test in a bigger szenario and come back with my results.

Thank you very much

**Comment by Firestorm87** [comment]
Hi, @saig0

seems to work.
But for better usability it would be nice to add support for these structures to the parser.
Is it possible?

**Comment by saig0** [comment]
Thank you for the feedback!

I agree that it would be nice. But it is hard with the current parser library. The FEEL grammar is recursive (left and right). It is tricky to handle the recursion without running into a loop. Maybe, I have a better chance when using a different parser library.

For now, I'll close the issue and keeping it in mind.
