### ISSUE TITLE
Evaluation fails if the variable name contains a date-time keyword

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#184]
**Describe the bug**

The evaluation of an expression fails if a variable name contains a date-time keyword (e.g. `date`, `time`, `duration`). 

```
failed to evaluate expression 'duration(timer_duration)': no variable found for name 'cellInput'
```

Related to #147

**To Reproduce**
1. Evaluate the expression `timer_duration` with a variable "timer_duration" 
2. Verify that the evaluation failed with a message `no variable found for name 'cellInput'`

**Expected behavior**
A variable name can contain a date-time keyword.

**Environment**
* FEEL engine version: 1.12.0
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: [0.x]

**Comment by AnatolyKostrikov** [comment]
@saig0 , good day. 
I found a similar error. So the reason might be the use of a dot in a variable name.

> EXTRACT_VALUE_ERROR | failed to evaluate expression ' dinner.meal = "salad"': no variable found for name 'dinner'

**Comment by saig0** [comment]
> I found a similar error. So the reason might be the use of a dot in a variable name.

@AnatolyKostrikov thank you for reporting. However, this is a different issue. :smiley: 

In the example, the user form defines a field with the key `dinner.meal`. On completing the form, it creates a process instance variable with the name `dinner.meal`. The instance fails to evaluate the condition on the exclusive gateway `dinner.meal = "salad"` and creates an incident.

As mentioned in the documentation [here](https://docs.camunda.io/docs/components/concepts/variables/#variable-names), a variable name may not contain an operator like a dot.

To avoid confusion like this, I recommend to create a bug issue in the Camunda Modeler project [here](https://github.com/camunda/camunda-modeler/issues). 

Does this make sense for you?
