### ISSUE TITLE
A way to know which variables that an expression depends on

### ISSUE THREAD

**Issue by ngochai94** [camunda/feel-scala#192]
I'm trying to invoke the following function
```
val expressionStr = "if (foo) then bar else baz"
engine.evalExpression(expressionStr, variableMap)
```
However, in my case, it's inefficient to feed all variables I have to the `variableMap`, e.g. I have million of them where each variable is stored in a separate file.

Is there a way to know which variables that `expressionStr` depends on? e.g. Something like this:
```
def getVariables(expression: String): List[String] = ???
getVariables(expressionStr) // == List("foo", "bar", "baz")
```

**Comment by saig0** [comment]
@ngochai94 is it sufficient for you to use a [CustomContext](https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/context/CustomContext.scala) instead: 

```
val myCustomContext = new CustomContext {

      override def variableProvider: VariableProvider = new VariableProvider {
        override def getVariable(name: String): Option[Any] = // ...
        override def keys: Iterable[String] = // ...
      }

    }

engine.evalExpression("a", myCustomContext) 
```

It allows loading the variables when they are accessed within the expression (i.e. lazy loading). 

API: https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/FeelEngine.scala#L145
A test case: https://github.com/camunda/feel-scala/blob/master/src/test/scala/org/camunda/feel/api/context/CustomContextTest.scala#L49

**Comment by ngochai94** [comment]
Thanks a lot @saig0 ! That's what I need.
