### ISSUE TITLE
Run all tests with Maven / SBT

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#22]
AT:
* I can run all tests of all modules with Maven / SBT

**Comment by hannes-o-brunner** [comment]
@saig0 
Just trying to run the tests in each module: While the factory test works, the plugin test crashes (without having applied any changes from my side).
Before I spend too much time hunting it down, does this work for you?
I get the following when running `sbt test` in the plugin subproject:

[info] CamundaFeelEnginePluginTest:
[info] A Camunda engine with FEEL Scala plugin
[info] - should has FEEL Scala Factory
[info] - should set default expression languages
[info] Exception encountered when attempting to run a suite with class name: org.camunda.feel.CamundaFeelEnginePluginTest *** ABORTED ***
[info]   org.camunda.bpm.engine.ProcessEngineException: ENGINE-03017 Could not perform operation 'drop' on database schema for SQL Statement: 'alter table ACT_RE_DECISION_DEF
[info] drop constraint ACT_FK_DEC_REQ'.
[info]   at org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.performDatabaseOperationException(EnginePersistenceLogger.java:221)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:668)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeSchemaResource(DbSqlSession.java:595)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.executeMandatorySchemaResource(DbSqlSession.java:407)
[info]   at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.dbSchemaDropDmn(DbSqlSession.java:398)
[info]   at org.camunda.bpm.engine.impl.db.AbstractPersistenceSession.dbSchemaDrop(AbstractPersistenceSession.java:136)
[info]   at org.camunda.bpm.engine.impl.SchemaOperationProcessEngineClose.execute(SchemaOperationProcessEngineClose.java:29)
[info]   at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
[info]   at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:104)
[info]   at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:66)
[info]   ...
[info]   Cause: org.h2.jdbc.JdbcSQLException: Tabelle "ACT_RE_DECISION_DEF" nicht gefunden
[info] Table "ACT_RE_DECISION_DEF" not found; SQL statement:
[info] alter table ACT_RE_DECISION_DEF
[info] drop constraint ACT_FK_DEC_REQ [42102-193]
[info]   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[info]   at org.h2.message.DbException.get(DbException.java:179)
[info]   at org.h2.message.DbException.get(DbException.java:155)
[info]   at org.h2.command.Parser.tableIfTableExists(Parser.java:5673)
[info]   at org.h2.command.Parser.commandIfTableExists(Parser.java:5686)
[info]   at org.h2.command.Parser.parseAlterTable(Parser.java:5511)
[info]   at org.h2.command.Parser.parseAlter(Parser.java:4844)
[info]   at org.h2.command.Parser.parsePrepared(Parser.java:344)
[info]   at org.h2.command.Parser.parse(Parser.java:317)
[info]   at org.h2.command.Parser.parse(Parser.java:289)
[info]   ...
Okt 02, 2017 10:16:43 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [mixed-dmn-config.cfg.xml]
[info] CamundaFunctionProviderTest:
[info] The function 'now()'
[info] - should return the current date-time *** FAILED ***
[info]   Mon Oct 02 10:16:44 CEST 2017 was not an instance of java.time.LocalDateTime, but an instance of java.util.Date (CamundaFunctionProviderTest.scala:43)
[info] The function 'currentUser()'
[info] - should return the current user id
[info] - should return null if no user is authenticated
[info] The function 'currentUserGoups()'
[info] - should return list of current group ids
[info] - should return null if no group is authenticated
Okt 02, 2017 10:16:44 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [override-dmn-config.cfg.xml]
[info] CamundaFeelEnginePluginConfigTest:
[info] A Camunda engine with FEEL Scala plugin
[info] - should set the DMN engine configuration
[info] - should extend an existing DMN engine configuration
[info] - should allow to override the default expression languages
[info] Run completed in 4 seconds, 911 milliseconds.
[info] Total number of tests run: 10
[info] Suites: completed 2, aborted 1
[info] Tests: succeeded 9, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         org.camunda.feel.CamundaFunctionProviderTest
[error] Error during tests:
[error]         org.camunda.feel.CamundaFeelEnginePluginTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 13 s, completed 02.10.2017 10:16:45

**Comment by saig0** [comment]
I've the same errors. I committed a fix :)

**Comment by hannes-o-brunner** [comment]
@saig0 See [PR](https://github.com/camunda/feel-scala/pull/23)

**Comment by saig0** [comment]
Done.
