### ISSUE TITLE
Strings can not contain double quotes

### ISSUE THREAD

**Issue by ProjectGuerilla** [camunda/feel-scala#236]
I'm trying to pass stings through the Zeebe engine and need to include double quotes in the strings ("). I have looked for ways to escape values and it is suggested that a \ should be able to escape a double quote but any attempt to pass a string that contains either a raw " or \" raises an error.

Attempting to do the same in the FEEL REPL running in scala is similarly unsuccessful.

It would be helpful if some mechanism of escaping a double quote was supported.

**Comment by saig0** [comment]
@ProjectGuerilla thank you for raising this up.

Please explain the use case in more detail, including the expression that you want to use. This helps to build it in the way you need it.

**Comment by ProjectGuerilla** [comment]
I'm working on a workflow builder that uses Zeebe. Part of the application uses an external app to collection information from users that gets passed between steps in the flow.

In one step we want to send email messages  based on strings that are a concatenation of template strings and data that is looked up from a DB. Because the email messages can be arbitrary they may contain " characters.

An example FEEL expression: "Morty said he'd be back \"Soon\" on " + date
(this is a contrived example) 
but no matter what I have tried to use for escaping the " character the FEEL expression always gives an errror.

**Comment by saig0** [comment]
Since DMN 1.2, escaped characters are allowed. See here: 
 
> ![image](https://user-images.githubusercontent.com/4305769/107908141-9f45ff00-6f55-11eb-858c-75a1064c111c.png)

> ![image](https://user-images.githubusercontent.com/4305769/107908170-aec54800-6f55-11eb-8d8f-097dfe42dbed.png)

**Comment by ProjectGuerilla** [comment]
I saw in the documentation that quoting of strings is supposed to be supported. What I am reporting is that I am unable to do this in practice.

The easiest way that I can represent this is in the SCALA FEEL REPL:
`@ feel(""" "a]"" """, content)
> Failure(failed to parse expression ' "a]"" ': [1.6] failure: end of input expected

 "a]""
     ^)`

We are having similar problems while attempting to send quoted strings inside FEEL expressions sent to Zeebe.

**Comment by saig0** [comment]
@ProjectGuerilla yes, sorry 🙈 I can reproduce the issue 👍 It is a valid request. My last comment was just a note for me (or any other contributed) on how to implement it. I'm sorry for the confusion 🍪
