### ISSUE TITLE
Exception with for* names of variables

### ISSUE THREAD

**Issue by maccory** [camunda/feel-scala#25]
Expression:
`if forename = "ALA" and birthDate > date("2000-01-01") then true else false`
produces exception:

> javax.script.ScriptException: failed to parse expression 'if forename = "ALA" and birthDate > date("2000-01-01") then true else false':
> [1.13] failure: `in' expected but `=' found
> 
> if forename = "ALA" and birthDate > date("2000-01-01") then true else false
>             ^

Expression:
`if surname = "ALA" and birthDate > date("2000-01-01") then true else false`
works fine.

I've found that variables with names beginning with "for" cause that problem.
Tested with version 1.2 in Java Spring application.

**Comment by saig0** [comment]
@maccory , thank you for reporting this bug!
