### ISSUE TITLE
Performance issue when using literal expressions

### ISSUE THREAD

**Issue by arneremeke** [camunda/feel-scala#29]
Hi Philipp,

in my setup (camunda 7.7 BPM-Platform CE, feel-scala as engine plugin 1.3.0-SNAPSHOT) I am experiencing performance issues when using literal expressions. If I evaluate an expression as input expression of a decision table, the evaluation of it is much faster in comparison to the evaluation of the same expression as literal expression (e.g. as input expressions in a table: 100 ms; as literal expression in a context object: 1000ms). 

Thank you so much for this feel engine! 

Kind regards
Arne

**Comment by saig0** [comment]
Hi Arne,

thanks for pointing this out. 

Can you please share your DMN file and your process engine configuration?
What expression do you evaluate?
How do you measure the time?

Best regards,
Philipp

**Comment by arneremeke** [comment]
Hi Philipp, 

I was able to reproduce the issue with a demo drd file. If you create a new literal expression and you select Feel from the Expression Language drop down list, the performance of the evaluation goes down (at least in my configuration). I could resolve the issue by removing the expressionLanguage="feel" attribute from the xml file. 

I created a REST Interface for the evaluation of the decision and measured the time from sending the request to the response with soap ui. 

Thanks a lot again, I am really happy about this extension and looking forward to use your feel implementation in several use cases :-) 

Best regards,
Arne

**Comment by saig0** [comment]
Hi Arne,

I'm happy to hear that you like the FEEL engine :smiley: 

Regarding the performance issue, when you don't select an expression language then the plugin uses 'feel-scala' as default. The Camunda DMN engine invokes the FEEL engine as script engine and caches the parsed FEEL expressions. 
If you set the expression language to 'feel' then the Camunda DMN engine invokes the FEEL engine via FEEL engine SPI that doesn't support caching. So when the DMN engine evaluates a decision then it needs to parse the expression every time.  

I hope this explains the performance differences.

Best regards,
Philipp

**Comment by arneremeke** [comment]
Hi Philipp,

thanks for the explanation! 

Best regards,
Arne
