### ISSUE TITLE
Date literal as @ notation

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#297]
**Is your feature request related to a problem? Please describe.**
I can define a temporal literal with the `@"..."` notation.

![image](https://user-images.githubusercontent.com/4305769/125280916-e7efc180-e315-11eb-90ba-712e27069173.png)

```
date("2021-07-12")

// same as

@"2021-07-12"
```

**Describe the solution you'd like**
Allow defining a temporal literal with the `@` notation as described in the specs.

**Related issues**

* Camunda BPM: 
* Zeebe broker:

**Comment by P3trur0** [comment]
I may take a look to this as well. Should this `@` work for `date` conversion only? Or does it apply to other conversions, e.g.: `date and time`?

**Comment by saig0** [comment]
@P3trur0 thank you for your offer :+1: But I already started working on it ([here](https://github.com/camunda/feel-scala/tree/297-temporal)) :sweat_smile:
