### ISSUE TITLE
Provide custom data transformer for the Camunda DMN engine

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#30]
Goal: Make it easier to use FEEL data types (time, local-time, date, date-time, local-date-time, year-month-duration, day-time-duration) in the Camunda DMN engine.

**Comment by saig0** [comment]
Supported data types:
* feel-date (java.time.LocalDate)
* feel-time (java.time.OffsetTime)
* feel-local-time (java.time.LocalTime)
* feel-date-time (java.time.OffsetDateTime)
* feel-local-date-time (java.time.LocalDateTime)

**Comment by saig0** [comment]
**TODO:** add description to the wiki and refer to Camunda docs: https://docs.camunda.org/manual/latest/user-guide/dmn-engine/embed/#customizing-and-extending-the-dmn-engine

**Comment by vdenisov** [comment]
Sorry for necroposting, but I wonder why there's no built-in transformations for duration types? As it stands, I can't use duration types in DMN without getting warnings like `DMN-01006 Unsupported type 'XXX' for clause` (where XXX is whatever type I tried to supply in my DMN definiton). It still works, but it would've been cleaner if there would've been an explicit transformer...

**Comment by saig0** [comment]
I agree. It would be nice if the modeler and the Camunda DMN engine supports all FEEL types :+1: This will come eventually (probably mid of 2022).

Please note that the data transformers were part of the Camunda engine plugin. But this part was removed with `1.11.0` (almost 2 years ago) when the FEEL engine was integrated in Camunda BPM. It is not the responsibility of the FEEL engine anymore - instead, it belongs to the Camunda DMN engine. 

Feel free to create an issue in the Camunda BPM project.
