### ISSUE TITLE
Numeric literal with leading zeros

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#301]
**Describe the bug**
It fails to parse a numeric literal if it has leading zeros (e.g. `01`, `001`).

**To Reproduce**
Evaluate the expression 

```
01
```

![image](https://user-images.githubusercontent.com/4305769/125393172-bb848580-e3a7-11eb-855f-1542ceffa9e2.png)

**Expected behavior**
Allow numeric literals with leading zeros as described in the spec.

![image](https://user-images.githubusercontent.com/4305769/125393041-824c1580-e3a7-11eb-8fed-5ea4dfbce93a.png)

**Environment**
* FEEL engine version: 1.13.2
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: [0.x]

**Comment by sccalabr** [comment]
I'd like to give this a try if you could point me to the rough location

**Comment by saig0** [comment]
@sccalabr go for it 🚀 

The number literal is defined in the parser here: https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala#L297

It might be already fixed in the `master` branch. But we don't have a test case yet. First, you could write a test case here: https://github.com/camunda/feel-scala/blob/master/src/test/scala/org/camunda/feel/impl/interpreter/InterpreterLiteralExpressionTest.scala
And update the docs.

**Comment by sccalabr** [comment]
What document would need to be updated if the spec says that we should allow leading zeros?
