### ISSUE TITLE
UnaryTests: compare a list with a single value

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#308]
**Is your feature request related to a problem? Please describe.**
In a unary-tests, I want to compare a variable with the input value. If the variable evaluates to a list then it fails to evaluate the expression because it expects a single value.

It works if the variable is replaced with a literal of the same value.

![image](https://user-images.githubusercontent.com/4305769/127957972-bd98e2ff-a1e0-46a6-aeee-c741362f0656.png)

**Describe the solution you'd like**
In a unary-tests, I can compare a variable with the input value if the variable evaluates to a list.

**Related issues**
Related to #307.

* Camunda BPM: 
* Zeebe broker:

**Comment by sccalabr** [comment]
Id also like to give this a try

**Comment by saig0** [comment]
The issue is fixed since version `1.14.0`.
