### ISSUE TITLE
I can invoke a function with a named parameter that contains whitespaces

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#311]
**Is your feature request related to a problem? Please describe.**
I can invoke a function with a named parameter. 

If the named parameter contains whitespace then the engine fails to parse the expression. 

**Describe the solution you'd like**
A named parameter of a function invocation can contain whitespaces.

**Related issues**

* Camunda BPM: 
* Zeebe broker:

**Comment by P3trur0** [comment]
Can I look at this, please?

**Comment by saig0** [comment]
@P3trur0 I'm sorry 😅  but the issue itself should be fixed after the refactoring of the parser. See here: https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala#L450

However, there is [no test case](https://github.com/camunda/feel-scala/blob/master/src/test/scala/org/camunda/feel/impl/interpreter/InterpreterFunctionTest.scala) to prove that the issue us fixed. Feel free to contribute a test case 👍

**Comment by P3trur0** [comment]
Test added.
