### ISSUE TITLE
get entries() expects a different argument name

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#320]
**Describe the bug**
In the DMN 1.3 spec, the function `get entries()` defines the argument: `m` .

But in the engine, the function expects the argument: `context`. 
Background: the function was introduces in the engine before it was introduced in DMN 1.3. 

**To Reproduce**
1. Evaluate the expression 
```
get entries(m:{a: "foo"})
```
2. Verify that the expression evaluates to `null` instead of `"foo"` 

**Expected behavior**
The `get entries()` function can be invoked with the named parameter: `m`.

For backward compatibility, the function should still support the argument: `context`.

**Environment**
* FEEL engine version: `1.13.2`
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: [0.x]

**Comment by P3trur0** [comment]
May I take this, please?
