### ISSUE TITLE
Describe possible variable names

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#334]
## Which documentation is missing/incorrect?

Describe how a variable should look like (i.e. alphanumeric with `_`), the limitations (e.g. no whitespaces/symbols, reserved words), and workarounds (e.g. escaped names, `get entry()`).

Link to the documentation:
* https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-variables
* https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-data-types#context

Affected versions:
* 1.14+

**Comment by kaaquist** [comment]
Can I grab this here?

**Comment by saig0** [comment]
@kaaquist yes, go for it. :rocket:
