### ISSUE TITLE
Support async functions

### ISSUE THREAD

**Issue by jbgi** [camunda/feel-scala#37]
Thanks for awesome project.

I have some function that I'd like to be invoked asynchronously.
A way, that induce a breaking change, would be modifying `ValFunction` to something like:
```scala
case class ValFunction(
    params: List[String],
    invoke: Either[List[Val] => Val, Async]
    hasVarArgs: Boolean = false,
    requireInputVariable: Boolean = false) extends Val {

    val paramSet: Set[String] = params.toSet
}
trait Async {
  def apply(args: List[Val])(implicit ec: ExecutionContext): Future[Val]
}
```
alternatively there could be a new `ValAsyncFunction`.

And then there would be new method in `FeelInterpreter`:
```scala
def evalAsync(expression: Exp)(implicit context: Context, ec: ExecutionContext): Future[Val]
```
to avoid duplication the current `eval` could be implemented as such:
```scala
def eval(expression: Exp)(implicit context: Context): Val = {
  implicit val sameThreadExecutionContext = ExecutionContext.fromExecutor(_.run())
  Await.result(evalAsync(expression), Duration.Inf)
}
```

Would you be open to such a feature?

**Comment by saig0** [comment]
Hi @jbgi ,

can you please tell me more about your use case?
Why do you need an asynchronous function?

Best regards,
Philipp

**Comment by jbgi** [comment]
Hi @saig0 

my current use case is to implement a function that convert amounts from one currency to another. Implementation will rely on an remote service (hence the need for `Future`).
The currencies themselves are not known before evaluation, could be the result of other functions.

My fallback plan would be to run the evaluation once with a mock function that collect actual currency arguments, then call the remote service, then execute again the evaluation with a synchronous function properly implemented using results from previous remote call.

**Comment by saig0** [comment]
Thank you for your fast response. 
I'm not sure about supporting async functions. The problem is that FEEL / DMN is not designed for handling async behaviour.

Do you use the FEEL engine in the context of the Camunda process engine? 
If yes then you can model a process like:
  () --> [ request currencies from remote ] --> [ calculate amounts ] --> ()

**Comment by jbgi** [comment]
I am not using the process engine only, the feel-engine.

But anyway I think I can use the pattern suggested: I can locally cache all the rates I can potentially need (it's not that big) before constructing the function.

Thanks for your prompt feedback.
