### ISSUE TITLE
Align with new string join() built-in function

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#372]
**Is your feature request related to a problem? Please describe.**
A new built-in function `joining()` was implemented with #339. In the meantime, a new built-in function `string join()` was defined for DMN 1.4 that provides the same logic. 
 

**Describe the solution you'd like**
Since the new function is not available in a released version yet, we should rename the function from `joining()` to `string join()` to align with the specs. 

![image](https://user-images.githubusercontent.com/4305769/147450422-2175ef4a-2f7f-448c-a5ac-b77e3eca8088.png)

Open TODOs: 
* rename function to `string join()`
* ignore `null` items in the list
* handle `null` as empty `delimiter` 
* write documentation

**Related issues**

* Camunda BPM: 
* Zeebe broker: 
* OMG: https://issues.omg.org/browse/DMN14-116

**Comment by P3trur0** [comment]
may I take this, please?

**Comment by saig0** [comment]
@P3trur0 of course :tada: go for it :rocket:

**Comment by P3trur0** [comment]
@saig0 I see that documentation pages for 1.14 have been removed. So, is it fine to document the function under:
[docs/docs/reference/builtin-functions/feel-built-in-functions-list.md](https://github.com/camunda/feel-scala/blob/master/docs/docs/reference/builtin-functions/feel-built-in-functions-list.md)?

**Comment by saig0** [comment]
Yes please 👍
