### ISSUE TITLE
Date conversion function

### ISSUE THREAD

**Issue by richardmward** [camunda/feel-scala#40]
Hi,

I am getting to grips with FEEL, and so I may be doing something wrong rather than this being an issue - so I apologise up front if that is the case!

If I try to run `date("2012-12-25") - date("2012-12-24") = duration("P1D")`, then I get a warning `WARN org.camunda.feel.FeelEngine - Suppressed failure: expected Number, Date, Time or Duration but found 'ValDate(2012-12-25)'` and returns `false` rather than `true`.

Interestingly if I change the expresssion to be `date and time("2012-12-25T00:00:00") - date and time("2012-12-24T00:00:00") = duration("P1D")`, then it does not cause a warning and returns `true` as expected.

I am executing the expressions via the `ScriptEngineManager` and am calling it using Java rather than Scala (which I have never experienced before this - and as such I have attempted to debug into it, but I have been unable work out how to!)

**Comment by saig0** [comment]
Hi @richardmward ,

according to the spec, it seems that you can't subtract a date from a date. Please have a look at the chapter 10.3.2.12 (table 45, page 123).

Do you agree with me?
Or do I miss something?

Best regards,
Philipp

**Comment by richardmward** [comment]
I had a feeling that it would be my limited knowledge of the FEEL specification - I agree with your interpretation that subtraction on a date is not a specified feature.

Many thanks for the reply - I'll close the issue.

**Comment by saig0** [comment]
I understand your confusion and I would also expect such a function. Maybe we should just add the missing function.

**Comment by saig0** [comment]
@richardmward , do you want to provide a pull request? 
I know that you have no experience in Scala but it's not that hard. You need to add some lines here: https://github.com/camunda/feel-scala/blob/master/feel-engine/src/main/scala/org/camunda/feel/interpreter/FeelInterpreter.scala#L399   and write some test cases.
