### ISSUE TITLE
Can't use variable in a expression contains "for ....if"

### ISSUE THREAD

**Issue by aisong** [camunda/feel-scala#414]
**Describe the bug**

My expression is :  `= for x in data return if (x.idx <= 2) then 1 else 555`
It failed when validate the expression: 
`failed to parse expression ' for x in data return if (x.idx <= 2) then 1 else 555': Expected (listIterator.rep(1) ~ \"return\" | binaryComparison | between | instanceOf | in | \"and\" | \"or\" | end-of-input):1:6, found \"x in data \"`

**To Reproduce**
1.  Expression parseExpression = expressionLanguage.parseExpression(expression);
2. get the failure message.

**Expected behavior**

The variable data is: 
`[{"name":"name_0","idx":0},{"name":"name_1","idx":1},{"name":"name_2","idx":2},{"name":"name_3","idx":3},{"name":"name_4","idx":4}]
`
I want to iterate the list and do something with each item,then return a new item.

**Environment**
* FEEL engine version: [1.14.1]

**Comment by saig0** [comment]
@aisong thank you for reporting :+1: 

The bug is already fixed in version [1.14.2](https://github.com/camunda/feel-scala/releases/tag/1.14.2) :rocket: 

![image](https://user-images.githubusercontent.com/4305769/163181130-e0dc7c7c-13b4-4a5d-b356-0b0a55a97e35.png)

**Comment by aisong** [comment]
OK,Thanks!
