### ISSUE TITLE
Hope the expression support code comment

### ISSUE THREAD

**Issue by aisong** [camunda/feel-scala#415]
**Is your feature request related to a problem? Please describe.**

The expression is very strong,I like it very well.

In some complex use cases, for clearer reasons, it needs to be done in several steps。
For example:
{
step1: xxx,
setp2: yyy,
step3: zzz,
result: xxx
}.result

**Describe the solution you'd like**

I want to add some "code comment" in the "expression code",just like:

{
step1: xxx, // this is step 1
setp2: yyy, // this is step 2
step3: zzz, // ...
result: xxx
}.result

**Related issues**

Can I do that?

Camanda platform: 8.0.0
feel-engine: 1.4.2

**Comment by saig0** [comment]
Hi @aisong :wave: 

Comments are already supported. Your example should work as expected. Have a look at the docs: https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-expressions-introduction#comments
