### ISSUE TITLE
Learning material for the FEEL language

### ISSUE THREAD

**Issue by korthout** [camunda/feel-scala#427]
## Which documentation is missing/incorrect?

* Learning material that leads the reader through exploring the FEEL language.

This could be inspired by other great language guides (https://doc.rust-lang.org/book/, http://www.learnyouahaskell.com/, etc)

Currently, the documentation is more reference-based:
* Getting Started: https://camunda.github.io/feel-scala/docs/reference
* What is FEEL: https://camunda.github.io/feel-scala/docs/reference/what-is-feel

Affected versions:
* 1.15

**Comment by saig0** [comment]
We made progress during the Summer Hack Days 2022. The result is published to https://camunda.github.io/feel-scala/docs/tutorial/
