### ISSUE TITLE
Boolean Expressions: Parsing error when using Conjunction ("And") or Disjunction ("Or")

### ISSUE THREAD

**Issue by aeberhardo** [camunda/feel-scala#429]
**Describe the bug**

We use FEEL in Camunda's DMN tables to evaluate expressions.
After we upgraded from Camunda `7.16.7` (with FEEL `1.13.3`) to `7.17.1` (FEEL `1.14.2`) we discovered a parsing error in FEEL when it comes to evaluating boolean expressions.

![image](https://user-images.githubusercontent.com/1492127/169830172-3bc84bf0-f36d-46b2-bf6e-e2f025fd30d3.png)

`FEEL/SCALA-01008 Error while evaluating expression: failed to parse expression 'true and null': Expected ("," | end-of-input):1:6, found "and null"`

Before the upgrade the expression "true and null" could be evaulated without problems and resulted in "null" (which is in line with https://camunda.github.io/feel-scala/docs/1.14/reference/language-guide/feel-boolean-expressions/#conjunction--and).

When the expression is enclosed in paretheses tha parsing error does not appear. So this is OK: `(true and null)`
The same problem also arises when using `or` in a boolean expression, e.g. `true or true`

**To Reproduce**
1. Create a DMN table in Camunda modeler like in the screenshot above.
2. Call `DmnDecisionTableResult.getDecisionResult(..)`

**Expected behavior**
No parsing error should occur when two booleans are combined with `and` or `or`.

**Environment**
* FEEL engine version: [1.14.2]
* Affects: 
  * Camunda Automation Platform 7: [7.17.1]

**Comment by saig0** [comment]
@aeberhardo thank you for reporting :+1: I can confirm the parsing error.
