### ISSUE TITLE
Functions `put all` and `context` do not propagate errors to the result

### ISSUE THREAD

**Issue by pihme** [camunda/feel-scala#446]
**Describe the bug**
Currently the built-in functions `put all` and `context` do not propagate errors that are passed in as argument. Instead, they return `null` in these cases and the error gets lost.

This is the root cause for: https://github.com/camunda/zeebe/issues/9543

**To Reproduce**
see ticket linked above

**Expected behavior**
* If an error is passed in, this error should be returned as the result of the function
* If multiple errors are passed in, the first error should be returned as the result of the function

**Environment**
* FEEL engine version: master
* Affects: 
  * Zeebe broker: https://github.com/camunda/zeebe/issues/9543

**Comment by pihme** [comment]
Implementation was started in branch `446-propagate...`

It is currently blocked by #260

**Comment by saig0** [comment]
We will not work on this issue. Instead, we will look at the topic when implementing custom error handling. 
The goal would be that the function returns `null` and reports an error.
