### ISSUE TITLE
use context as map or function

### ISSUE THREAD

**Issue by jbgi** [camunda/feel-scala#46]
eg. 
```
 { "a" : 1 }["a"] = 1
```
or
```
 { "a" : 1 }("a") = 1
```
not sure how this would integrate/clash with the DMN spec... ?

**Comment by saig0** [comment]
You can access a context entry by key: `{a: 1}.a`.

Is this what you're looking for?

**Comment by jbgi** [comment]
no, in my case the path is the value of a variable in the context.

**Comment by jbgi** [comment]
Alternatively I use a list of if/then/else but I'd be very keen to have a better way to express this kind of stuff. I was thinking of using context but pattern matching support will be even better.

**Comment by saig0** [comment]
In the spec, I found the proposal of a built-in function:

`get entries({key 1 : "value 1 "})[key="key 1 "].value = "value 1 "`

and 

`get value({key 1 : "value 1 "}, "key 1 ") = "value 1 "`

What do you think?

**Comment by jbgi** [comment]
yes, that would quite fit the use case!

**Comment by saig0** [comment]
Do you want to implement the `get value` built-in function?

**Comment by jbgi** [comment]
Yeah, I can give it a try.
Do you have a suggestion of an existing PR that I could take as an example?
