### ISSUE TITLE
Wrong check boolean value expression with evalExpression or eval

### ISSUE THREAD

**Issue by zacisco** [camunda/feel-scala#464]
**Describe the bug**
use free-scala as java dependency in project
test rule:
field: active - true
data: active - false
and check always return "true" as result
i mean lib get rule expression and return it as result without check
`engine.evalUnaryTests("true", Map.of("cellInput", false))` is worked

**To Reproduce**
`engine.evalExpression("true", Map.of("cellInput", false))`
or
`engine.eval(engine.parseExpression("true").toOption().get(), Map.of("cellInput", false))`

**Expected behavior**
result should be false as ckeck result

**Environment**
* FEEL engine version: [1.15.1]

**Comment by zacisco** [comment]
what different between eval,evalExpression and evalUnaryTests?

**Comment by zacisco** [comment]
what different between eval,evalExpression and evalUnaryTests?

**Comment by saig0** [comment]
@zacisco thank you for creating this issue. I'm not sure about your actual question and your expectations. Let me try to clarify things.

If I evaluate the unary-tests expression `true` with an input value `true` then it returns `true`. If the input value is `false` then it returns `false`.

![image](https://user-images.githubusercontent.com/4305769/183378826-bf345b2e-c547-4731-b901-ea299d364771.png)

Expressions are different. An expression doesn't compare the given literal (e.g. `true`) with a given input value. Unary-tests expressions expect an implicit input value to compare to. But not expressions. Read more about it in the docs: https://camunda.github.io/feel-scala/docs/reference/what-is-feel#unary-tests-vs-expressions

`engine.evalExpression(...)` and `engine.eval(parsedExpression, ...)` evaluate an expression but no unary-tests expression. If you try to evaluate a unary-tests expression then use `evalUnaryTests(...)` instead.

@zacisco does this make sense for you?

**Comment by zacisco** [comment]
yep ... it's my fault,i think )
eval return some result after calculate expressions
unary return logic result after calculate and compare
