### ISSUE TITLE
External function definition with argument Map or List

### ISSUE THREAD

**Issue by arneremeke** [camunda/feel-scala#48]
My external function returns all Values from a context(java.util.Map) as List. This fails with error: fail to invoke method with name 'getValues' and arguments 'List(java.util.Map)' from class 'dmn.externalfunctions.Context').

```
FEEL Literal Expression
{
  "get_values": function(object) external { 
    java: { 
        class: "dmn.externalfunctions.Context", 
        method_signature: "getValues(java.util.Map)" 
          } 
     },
"my_object": {
   "a": input.a instance of string or input.a = null,
   "b": input.b instance of number,
   "c": input.c instance of list,
   "c1": every c1 in input.c satisfies c1 instance of boolean,
   "d": input.d instance of context
    },
    "valid": every value in get_values(my_object) satisfies value
}
```
 ```
Java External Function 
public static ArrayList getValues(Map<String, Object> myMap) {
		   return new ArrayList(myMap.values());
	  }
```
How to define external functions with complex types like Maps or Lists? 

Arne

**Comment by meyerdan** [comment]
Hi Arne,

Just a heads-up: @saig0 , the maintainer of this library is currently out of office, it could take some time before you get an answer ...

**Comment by arneremeke** [comment]
Hi Philipp,

even if my new function is not fully functional yet, I am able to create a new function with JavaFunctionProvider and can invoke it from my FEEL literal expressions. Ticket can be closed! 

Kind regards,
Arne

**Comment by saig0** [comment]
@arneremeke , I'm happy that you found a way. Also, I created a new issue #49 to add built-in functions which may help you in the future.
