### ISSUE TITLE
Playground can't display legitimate `false` return values

### ISSUE THREAD

**Issue by upgradingdave** [camunda/feel-scala#504]
## Which documentation is missing/incorrect?

The playground should display `false` if an expression evaluates to `false`.  The current implementation assumes a `result` of `false` indicates an error. However, the result can also legitimately be `false` (without an error). 

Link to the documentation:
* https://camunda.github.io/feel-scala/docs/playground/

Affected versions:
* 1.16.0-SNAPSHOT

**Comment by saig0** [comment]
@upgradingdave nice catch :+1:
