### ISSUE TITLE
Add new built-in function to generate random numbers

### ISSUE THREAD

**Issue by aisong** [camunda/feel-scala#506]
I want a function that can generate random number.

I can't find it in the current documents.Can you add one? 

Thanks!

**Comment by saig0** [comment]
@aisong thank you for raising this up. Please add more details about 
* your use case for the new function 
* your preferred function signature for the new functions (i.e. arguments)

**Comment by aisong** [comment]
> 

I want the function just like this(for example,in nodejs):

> Math.random()
0.9701618132579795

@saig0  Thank you for your reply!

**Comment by saig0** [comment]
Suggestion:

* add a new function with the name `get random number`
* the function takes no arguments
* it returns a (floating point) number between `0` and `1`

```
get random number()
```

@aisong does this look good for you?
I'm still interested to hear about your use case. :wink:

**Comment by aisong** [comment]
@saig0 I'm sorry for not seeing your reply for so long.

Your suggestion is very cool 👍 , it's what I want！

My current user case is that I need to do random sampling from a long list.And I think this method is also needed in many other scenarios.

**Comment by kaaquist** [comment]
@saig0 Is this here up for grabs ? (hacktoberfest)

**Comment by saig0** [comment]
@kaaquist yes, go for it. :rocket:
