### ISSUE TITLE
Get a date-time in a given zone 

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#508]
**Is your feature request related to a problem? Please describe.**
I want to represent a given date-time value at a different timezone (i.e. changing the timezone). Currently, there is no function or operator to change the timezone. The only option is to build the string representation manually. 

**Describe the solution you'd like**
Add a new built-in function to create a new date-time in the given zone. Or, extending the existing conversion function:

Suggestion:

```
date and time(date-time, timezone)
// date-time -> a date and time value
// timezone -> a string value that defines the target zone id 
```

Usage:

```
date and time(@"2020-07-31T14:27:30@Europe/Berlin", "Z")
// returns date and time("2020-07-31T12:27:30Z")

date and time(@"2020-07-31T14:27:30@Europe/Berlin", "America/Denver")
// returns date and time("2020-07-31T06:27:30@America/Denver")
```

The implementation should work similarly to the following equivalent from Java:

```
dateTime.withZoneSameInstant(ZoneId.of("America/Denver")) 
``` 

**Related issues**

* Support case: https://jira.camunda.com/browse/SUPPORT-14012
* Camunda Autormation Platform 7: 
* Zeebe broker:

**Comment by sccalabr** [comment]
Id like to give this a try

**Comment by saig0** [comment]
@sccalabr yes, go for it. :rocket: 

Don't forget to 
- write new test cases [here](https://github.com/camunda/feel-scala/blob/main/src/test/scala/org/camunda/feel/impl/builtin/BuiltinConversionFunctionsTest.scala)
- update the docs [here](https://github.com/camunda/feel-scala/blob/main/docs/docs/reference/builtin-functions/feel-built-in-functions-conversion.md)

**Comment by sccalabr** [comment]
How do you convert a valDate back to a date? I am trying to do something like
```
 private def getDateTimeInZone(date: Date, zone: String): ValDateTime = {
    ValDateTime(date.toLocalDate.toInstant().atZone(ZoneId.of(zone)))
  }
  
  or
  
  private def getDateTimeInZone(date: Date, zone: String): ValDateTime = {
    ValDateTime(date.toInstant().atZone(ZoneId.of(zone)))
  }
``` 

but im getting things like
value toLocalDate is not a member of org.camunda.feel.Date
value toInstant is not a member of org.camunda.feel.Date

This is what I am currently working at. Let me know if anything is completely off. 
https://github.com/camunda/feel-scala/compare/main...sccalabr:feel-scala:508?expand=1

**Comment by saig0** [comment]
@sccalabr I'm sorry. The description of the issue was not clear enough. 

The parameters of the function should be:
- `date`: the source date as a `date-time` value 
- `timezone`: the target timezone (i.e. the zone-id) as a `string` value

The target date-time can be calculated by using the following function: 

```
ValDateTime(dateTime.withZoneSameInstant(ZoneId.of(zoneId)))
```

Note that a date value doesn't have a timezone. Only a time or a date-time can be defined in a timezone.
