### ISSUE TITLE
negative durations in string variables fail to parse

### ISSUE THREAD

**Issue by cameronbraid** [camunda/feel-scala#513]
negative durations work when they are literal strings
`feel("""duration("PT-5M")""", context)` works

however when they are string variables they don't 

`feel("""duration(durationBefore)""", Map("durationBefore" -> "PT-5M"))` shows error

```
12:42:40.918 [main] WARN  org.camunda.feel.FeelEngine - Failed to parse duration from 'PT-5M'
```

**Comment by cameronbraid** [comment]
I should also point out that the following also works

`feel("""duration(durationBefore)""", Map("durationBefore" -> "-PT5M"))`

so its just negative durations where the `-` sign is after the `P` when its a string varaible

**Comment by saig0** [comment]
@cameronbraid good catch :+1: 

Negative durations are not explicitly mentioned in the DMN spec. However, if I look at [Java's Duration class](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)) then each number can have a negative or positive sign.   

We should ensure that the literal is working in the same way as the conversion function [duration()](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/feel-built-in-functions-conversion/#duration).

**Comment by sccalabr** [comment]
id like to give this a try

**Comment by saig0** [comment]
@sccalabr I appreciate your passion. I assigned two other issues already to you. Please finish the other ones first. :sweat_smile:

**Comment by sccalabr** [comment]
@saig0 I have completed 1 and issue and the other 1 is out for review. Can I take this up now? Also how would I go about writing a unit test for this? I havent seen any tests so far that would like """feel(...)"""

**Comment by saig0** [comment]
@sccalabr yes, go for it. :rocket: 

In the description, @cameronbraid used the [FEEL REPL](https://camunda.github.io/feel-scala/docs/reference#feel-repl) to test the expressions. You can ignore the `feel(...)` wrapper around the expression for the unit tests.

**Comment by sccalabr** [comment]
Which function in the parser would need to be updated? Im looking for a map function but dont really see one.
