### ISSUE TITLE
Problem implementing Function Provider

### ISSUE THREAD

**Issue by octaviospain** [camunda/feel-scala#52]
I'm trying to implement a custom function so I can use it in FEEL expresions in a DMN decision table.
To do so I'm following the wiki page [Function Provider SPI](https://github.com/camunda/feel-scala/wiki/Function-Provider-SPI).
The resulting Java class that implements my class looks like this:
```java
public class CoalesceFunctionProvider extends JavaFunctionProvider {

    @Override
    public List<JavaFunction> resolveFunctions(String functionName) {
        if (functionName.equals("coalesce")) {
            Function<List<Val>, Val> function =
                    arguments -> arguments.stream()
                            .filter(Objects::nonNull)
                            .findFirst()
                            .orElse(null);

            List<String> params = Lists.newArrayList("args");
            return Collections.singletonList(new JavaFunction(params, function, true));
        } else {
            return Collections.emptyList();
        }
    }
}

```
in addition, I created a file named `org.camunda.feel.spi.CustomFunctionProvider` under the `META-INF/services` folder, as described in that page.

But when trying to use the function in a DMN decision table, inside a literal expression like:
```
coalesce(input1, input2, input3)
```

I get
```
org.camunda.bpm.dmn.feel.impl.FeelException: failed to evaluate expression 'coalesce(input1, input2, input3)':
no function found with name 'coalesce' and 3 parameters
```

1. What am I missing here?
2. Is the information shown in [this other wiki page](https://github.com/camunda/feel-scala/wiki/FEEL-Language-Guide) about defining new functions, meaningful for this purpose too?
It is not described how where and how to import that function definition into the engine.

**Comment by saig0** [comment]
@octaviospain, this looks good so far :+1: 

Do you use the FEEL engine as Camunda process engine plugin? 
How do you configure the plugin? 
Is the `JavaFunctionProvider` and the file in the classpath?

It would be good to add some log statements to see which provider is loaded :thinking:

**Comment by octaviospain** [comment]
I'm using the FEEL plugin inside a Spring Boot application, using gradle as a dependency and build tool:
```gradle
compile 'org.camunda.bpm.extension.feel.scala:feel-engine-plugin:1.5.0'
```
additionally I declare the plugin in a Spring configuration Java file
```java
@Configuration
public class BpmPlatformConfiguration {

    @Bean
    public ProcessEnginePlugin feelScalaPlugin() {
        return new CamundaFeelEnginePlugin();
    }
}
```
At the application startup, logs shows that the plugin is being used:
```
2019-01-22 09:55:59.982+0100 INFO [main] org.camunda.bpm.engine.cfg.logInfo : ENGINE-12003 Plugin 'CompositeProcessEnginePlugin[..., CreateAdminUserConfiguration[..., CamundaFeelEnginePlugin, ConnectProcessEnginePlugin, SpinProcessEnginePlugin]' activated on process engine 'default'
```
I found also this line, that might refer to the `META-INF/services/org.camunda.feel.spi.CustomFunctionProvider` file
```
2019-01-22 09:56:03.180+0100 INFO [main] s.d.s.w.p.DocumentationPluginsBootstrapper.start : Found 1 custom documentation plugin(s)
```
Loaded providers mentioned in the startup log:
```
2019-01-22 09:56:00.004+0100 INFO [main] org.camunda.spin.logInfo : SPIN-01010 Discovered Spin data format provider: org.camunda.spin.impl.json.jackson.format.JacksonJsonDataFormatProvider[name = application/json]
```
```
2019-01-22 09:56:00.053+0100 INFO [main] org.camunda.spin.logInfo : SPIN-01010 Discovered Spin data format provider: org.camunda.spin.impl.xml.dom.format.DomXmlDataFormatProvider[name = application/xml]
```

**Comment by saig0** [comment]
@octaviospain, can you try it again with the [new version 1.6.2](https://github.com/camunda/feel-scala/releases/tag/1.6.2)? In this version, you can see which function provider is loaded.

**Comment by octaviospain** [comment]
I updated the dependecy to version 1.6.2 and I see the same logs, nothing about any function provider loaded :/

**Comment by saig0** [comment]
In the log, you should see something like 
`11:08:43.061 [pool-5-thread-5] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: org.camunda.feel.spi.TestValueMapper@753cfc79, function-provider: org.camunda.feel.spi.TestFunctionProvider@67fc4a01]`

**Comment by octaviospain** [comment]
I don't. The only line matching 'FeelEngine' is
```
org.camunda.bpm.engine.cfg.logInfo : ENGINE-12003 Plugin '(...) CamundaFeelEnginePlugin' activated on process engine 'default'
```
I'm sure that the Feel Engine works because I've tested the usage of scala operators. What am I missing?

**Comment by saig0** [comment]
Can you share your project? That would help me to analyze the issue :)

**Comment by octaviospain** [comment]
I cannot. I will try to provide a SSCCE that isolates the behaviour and structure.

**Comment by octaviospain** [comment]
Here is the link to the SSCCE: [Camunda Spring Boot example](https://github.com/octaviospain/CamundaSpringBootExample)

It contains a test showing the mentioned output error.
The only difference I noticed when running it is this line in the logs:
`
2019-01-28 13:09:47.494  INFO 28346 --- [main] org.camunda.feel.FeelEngine : Engine created. [value-mapper: org.camunda.feel.integration.CamundaValueMapper@5e6bbe63, function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@69356aca]
`

**Comment by saig0** [comment]
Thank you for providing the example :+1:  I can reproduce the issue. It seems that there is a class loading problem when using Spring Boot. The function provider is loaded via Java's ServiceLoader.

**Comment by octaviospain** [comment]
Looks like we found a bug indeed. Was this proved to be working fine in previous versions? How can I help fixing it, any clues?

**Comment by saig0** [comment]
Finally, I found the "bug". The problem is that the expression language of the literal expressions is set to `feel`. If no expression language is set then the plugin set it to `feel-scala`. 

If it is set to `feel-scala` then the function provider (and value mapper) is loaded via service loader and everything just works. :balloon: But if it is set to `feel` then the providers are not loaded :see_no_evil: 

I'll change the behavior so that the function providers are also loaded in this case. #53

BTW: your `CoalesceFunctionProvider` doesn't work at it is. Let me know if I can assist you ;)

**Comment by octaviospain** [comment]
Great then, many thanks. I'm not involved in the project in which this was required anymore, but maybe eventually someone will and look around this :)
