### ISSUE TITLE
Get the last day of a given month 

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#526]
**Is your feature request related to a problem? Please describe.**
I want to calculate the last day of a given month. For example, to return a date that is due three days before the month ends.

Currently, I could use the following expression to calculate the date.

```
date(today().year, today().month, 1) + @"P1M" - @"P1D"
// "2022-09-30"
``` 

**Describe the solution you'd like**
Add a new built-in function to return the last day of the month.

- function: `last day of month(date)`
- parameters:
  - `date` - a date or date-time value
- returns: the last day of `date` as a date value  

```
last day of month(today())
// "2022-09-30"
```

**Related issues**

* Camunda Autormation Platform 7: 
* Zeebe broker:

**Comment by sccalabr** [comment]
Can I try this?
