### ISSUE TITLE
Interface to get list of Feel built-in function

### ISSUE THREAD

**Issue by mcb345** [camunda/feel-scala#56]
I would like to create a REST API for built-in FEEL expression and expected to return list of built in FEEL function (and if it is possible the custom function created by JavaFunctionProvider)

is there any way to return list of all the function ?

**Comment by saig0** [comment]
You can get the built-in functions here: https://github.com/camunda/feel-scala/blob/master/feel-engine/src/main/scala/org/camunda/feel/interpreter/BuiltinFunctions.scala#L24
The function providers can be accessed by the engine: https://github.com/camunda/feel-scala/blob/master/feel-engine/src/main/scala/org/camunda/feel/FeelEngine.scala#L53

I don't understand what exactly do you want to do. Please describe your use case in more detail.
What should the REST API do?

**Comment by saig0** [comment]
I'll close this issue for now. @mcb345 feel free to open it when you have any updates.
