### ISSUE TITLE
Handle non-existing variables and context entries gracefully in comparison and filter expressions

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#582]
**Describe the bug**
If I compare a non-existing variable with a value then the expression fails. To avoid failure, I must do a null check first.

```
x = 3
// failed to evaluate expression ' x = 3 ': no variable found for name 'x'

x > 3
// failed to evaluate expression ' x > 3 ': ValError(no variable found for name 'x') is not comparable

x != null and x = 3
// returns false
```

The behavior is the same for filter expressions.

```
[{x:5},{y:2}][x > 3]
// failed to evaluate expression ' [{x:5},{y:2}][x > 3]  ': ValError(no variable found for name 'x') is not comparable)

[{x:5},{y:2}][x != null and x > 3]
// returns [{x:5}]
```

Related [discussion](https://camunda.slack.com/archives/C01QYD808A3/p1671687820836529).
Related to https://github.com/camunda/feel-scala/issues/572.
Related to https://github.com/camunda/feel-scala/issues/260.

**To Reproduce**
1. Evaluate the expression `x = 5`
2. Verify that the expression is not successful

**Expected behavior**
A non-existing variable or context entry is handled gracefully in a comparison and a filter.

Instead of failing the evaluation, the comparison or filter handles the non-existing value as `null`. The comparison may return `false` or `null`. The filter doesn't include the list item in the result.

Since the engine handles the case gracefully, no warning should be printed. 

```
(null = 3) = false

(null < 3) = null

// 10.3.2.5 - example 3
[ { x: 1, y: 2 }, { x: null, y: 3 } ][ x < 2 ] = [ { x: 1, y: 2 } ]

// non-member matching
[ { x: 1 } ][ y > 1 ] = [ ]

[ { x: 1 }, { y: 2 } ][ y > 1 ] = [ { y: 2 } ]
```

**Environment**
* FEEL engine version: `1.15.2`
* Affects: 
  * Camunda Automation Platform 7: [7.x] 
  * Zeebe broker: [0.x]

**Comment by saig0** [comment]
Related to the issue https://github.com/dmn-tck/tck/issues/536 that points to the following section of the DMN spec:

![image](https://user-images.githubusercontent.com/4305769/213127796-854fc211-3c3e-458a-9640-fd08336d88a6.png)

**Comment by cjcalmeida** [comment]
I have a question about this topic:

We have an implementation that validates the expression (if the expression is valid and if the variables exist in the context) and we use FeelEngine (evalUnaryTests or evalExpression) today FeelEngine doesn't fail, it just emits a log warn level, but with
the complete DMN (when we put expression in DMN and run Camunda), the evaluate of the expression fails, because the variable does not exist.

Wouldn't it be better to have the same result in both cases?

I use Camunda Platform 7.17 (DMN 7.17 too)

**Comment by saig0** [comment]
> Wouldn't it be better to have the same result in both cases?

Yes. The FEEL engine should behave the same. However, the DMN (or BPMN) engine may raise an error (or incident) if the expression doesn't return a required value. 

It would be great if you could share your example. Happy to discuss it in detail.

**Comment by korthout** [comment]
@saig0, the ZPA team would like to work on this together with you. Do you think you would have time for that, or is there any way we can clarify what needs to happen here?

**Comment by saig0** [comment]
@korthout awesome. Let's schedule a pair/mob programming session (but not before 2023-04-24). We should plan for at least 2 hours of coding.

**Comment by korthout** [comment]
@saig0 I'll be unavailable for about two weeks starting April 26th. You may need to organize this with the team, or someone else from @camunda/zeebe-process-automation needs to arrange this.

**Comment by saig0** [comment]
:warning: Note that we change the behavior of less/greater than comparison with `null`. Previously, the comparison returned `false` (see https://github.com/camunda/feel-scala/issues/50). Now, the comparison will return `null` instead which is aligned with the DMN spec. Only two values of the same type are comparable.  

For example:
```
null < 5
// 1.16: false
// 1.17: null

non_existing < 5
// 1.16: failure
// 1.17: null

null between 1 and 10
// 1.16: false
// 1.17: null   

non_existing between 1 and 10
// 1.16: null
// 1.17: null
```

---

Side note: The DMN spec says that `null` should be used for NaN, positive and negative infinity. But `null` can't be used to compare with a number. So, it is not possible to check against infinity. In practice, this should not be relevant.

**Comment by remcowesterhoud** [comment]
Now that #676 is merged we have "completed" the non-existing variables in comparisons part. The filter expressions still need to be done!

During this I encountered two bugs:
- #679 
- #681

**Comment by korthout** [comment]
The team spend time on this during our weekly mob programming session, resulting in:
- #685

We'll continue it again next week

**Comment by korthout** [comment]
Moving this back to Ready, as there is one step left:
- null handling in filter expressions with contexts (see examples in issue description)
