### ISSUE TITLE
Regression in string conversion of zero-length duration

### ISSUE THREAD

**Issue by korthout** [camunda/feel-scala#598]
**Describe the bug**
There is a regression in 1.15.3 where the string conversion of a zero-length duration leads to a non-ISO 8601 representation: `P` instead of `PT0S`.

**To Reproduce**

```
===== FEEL Engine REPL (1.15.3) ======
> Evaluate FEEL expressions using 'feel("1 + 3")'
> Evaluate FEEL unary-tests using 'unaryTests("[2..5]", 4)'
> Provide variables as Map using 'feel("x + 3", Map("x" -> 2))'
> Provide variables as JSON string using 'feel("x + 3", "{ \"x\" : 2 }")'
Welcome to the Ammonite Repl 2.5.6 (Scala 3.2.1 Java 19.0.2)
@ feel("string(duration(\"P0D\"))")
> P

===== FEEL Engine REPL (1.15.2) ======
> Evaluate FEEL expressions using 'feel("1 + 3")'
> Evaluate FEEL unary-tests using 'unaryTests("[2..5]", 4)'
> Provide variables as Map using 'feel("x + 3", Map("x" -> 2))'
> Provide variables as JSON string using 'feel("x + 3", "{ \"x\" : 2 }")'
Welcome to the Ammonite Repl 2.5.6 (Scala 3.2.1 Java 19.0.2)
@ feel("string(duration(\"P0D\"))")
> PT0S
```

**Expected behavior**
The result should be `P0D`.

_EDIT: We changed the expectation from `PT0S` to `P0D` because of a DMN TCK test case. (see https://github.com/camunda/feel-scala/issues/598#issuecomment-1527173279)_

**Environment**
* FEEL engine version: 1.15.3
* Affects: 
  * Camunda Platform 8: >8.1.7 https://github.com/camunda/zeebe/issues/11967

**Comment by korthout** [comment]
We (Zeebe Process Automation) want to patch this, but wrapping up the Zeebe 8.2 release has our priority. Marking this as `later` so we may work on it after the 8.2 release.

**Comment by saig0** [comment]
Actually, the expected result should be `P0D`. 

I don't find anything concrete about it in the DMN spec. But there is a test case in the DMN TCK [here](https://github.com/camunda/dmn-tck/blob/0b613499cd5fe5c49bd99e8c89dc6a13bc425adb/TestCases/non-compliant/0079-feel-string-function/0079-feel-string-function.dmn#LL195C2-L203C16). 

![image](https://user-images.githubusercontent.com/4305769/235094135-39d4c60d-8344-4ae4-86cc-936e69628646.png)

We should align with the other vendors and pass the TCK test case.
