### ISSUE TITLE
Support null equality checks

### ISSUE THREAD

**Issue by hannes-o-brunner** [camunda/feel-scala#6]
The interpreter crashes for equality checks containing null values on either the left hand or right hand side.
F.ex. for a domain object with field `language,` which can be null, both `person.language = "German"` (if current person.language is null) and `person.language = null` crash

Quickfix in `FeelInterpreter.dualOpAny` as follows

```
if (x == ValNull || y == ValNull) {
  ValBoolean(x == y)
} else {
  // existing logic
}
```

**Comment by saig0** [comment]
Additionally, the engine should use **unary test** instead of **simple unary test** to support null checks also for 'tests'.

**Comment by saig0** [comment]
@hannes-o-brunner , do you want to create a pull request?

**Comment by hannes-o-brunner** [comment]
Submitted [PR](https://github.com/camunda/feel-scala/pull/8)
