### ISSUE TITLE
index of() returns empty list in case of first list element

### ISSUE THREAD

**Issue by bhoefman** [camunda/feel-scala#61]
**Describe the bug**
`index of()` returns empty list in case of first list element

**Expected behavior**
`index of(["a","b","c"],"a")`
- expected result: `[1]`
- actual result: `[]`

**Environment**
As Camunda BPM process engine plugin
version: 1.3.1

**Comment by saig0** [comment]
@bhoefman, thank you for raising this up. I can confirm the bug.
