### ISSUE TITLE
Unary test for negative number fails

### ISSUE THREAD

**Issue by nevries** [camunda/feel-scala#69]
**Describe the bug**
If I put a unary test in a DMN table with value "-1" to check if the input value equals the number -1, a parse error occurs.
Workaround is to use an interval containing only that number like "[-1..-1]".

**To Reproduce**
Following JUnit-Test-Code:
```
    ((VariableMapImpl) variables).putValue("minusOne", -1);
    Object o = feelEngine.evaluateSimpleUnaryTests("1", "minusOne", variables);
    assertThat(o).isEqualTo(false);
    o = feelEngine.evaluateSimpleUnaryTests("[-1..-1]", "minusOne", variables);
    assertThat(o).isEqualTo(true);
    o = feelEngine.evaluateSimpleUnaryTests("-1", "minusOne", variables);
    assertThat(o).isEqualTo(true);
```

**Expected behavior**
No parse error but correct check for equality.

**Environment**
1.8.0 as process engine plugin in Spring Boot.

**Comment by saig0** [comment]
Good catch and thank you for reporting :+1:

**Comment by saig0** [comment]
@nevries, let me know if you need a bugfix release for a specific date :)

**Comment by xlhtc007** [comment]
I also encounter this problem: https://forum.camunda.org/t/exception-of-number-comparison-with-negative-number-using-feel-scala-extension/15023.  hope to fix it as soon as possible, thanks!

**Comment by saig0** [comment]
@xlhtc007, thanks for letting me know. I wil build a path release this week.

**Comment by saig0** [comment]
@xlhtc007, the bugfix is release: https://github.com/camunda/feel-scala/releases/tag/1.8.1

**Comment by xlhtc007** [comment]
> @xlhtc007, the bugfix is release: https://github.com/camunda/feel-scala/releases/tag/1.8.1

thanks for your quick fix!
