### ISSUE TITLE
Custom context provider

### ISSUE THREAD

**Issue by hannes-o-brunner** [camunda/feel-scala#7]
First thanks for the nice library!

I am using feel-scala as an embedded expression interpreter from within a Scala program. There is some impedance mismatch between Java and Scala classes / objects which impedes direct access of given Scala domain objects and their properties with the supported Java context implementation.
F.ex. to specify a nullable property, in Scala it would be defined as `name: Option[String]`, another example is enumerations whose value are implemented as Scala case classes and their corresponding objects.
In order to seamlessly access the Scala domain objects, it would be helpful to be able to specify corresponding custom context providers, which - given an object of a certain base class / interface - could enumerate its properties (in a first step I only need properties, not methods).
Something like `contextProvider: (Superclass/MarkerInterface) -> Map[String, <FeelProperty>]`

My current workaround is to replace all the domain objects (and their nested entities, where necessary) into a `Map[String, Any]` before handing over the context to the feel interpreter. While this works, it is probably not that efficient, since I have to map the full domain model, as I do not know what is being accessed in the expressions (rather than having the interpreter doing context resolution only when necessary).

**Comment by saig0** [comment]
@hannes-o-brunner , do you only need to access fields of type `Option` and `Enumeration`?

```
it should "access option field" in {
 
   class A(val b: Option[Int])
    
    eval("a.b", Map("a" -> new A(Some(2)))) should be(ValNumber(2))
    eval("a.b", Map("a" -> new A(None))) should be(ValNull)
  }
  
  it should "access enumeration field" in {
    
    object WeekDay extends Enumeration {
      type WeekDay = Value
      val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
    }
    
    import WeekDay._
    class A(val b: WeekDay)
    
    eval("a.b", Map("a" -> new A(WeekDay.Mon))) should be(ValString("Mon"))
    eval("a.b", Map("a" -> new A(WeekDay.Fri))) should be(ValString("Fri"))
  }
``` 
Is this what you need? Do you need more?

===
Beside that it's nice to hear that you use the engine. I'm interested what you build with it. Can you please tell more about it?

**Comment by hannes-o-brunner** [comment]
@saig0 find a more precise sample of what I would like to support below

- `def` in `trait` instead of `val` (this probably does not matter)
- custom enum with `sealed case class`

Scala does not seem to have a one-fits-all implementation of Enumeration, so I suspect there might be the necessity to support different implementations / mappings? Hence my suggestion to let the domain provide the context resolution.

```
  "A scala domain object" should "be handled as context" in {
 
    sealed case class Language(val id: String)

    object Languages {
    	object DE extends Language("DE")
    	object EN extends Language("EN")
    }

    trait Person {
      def name: Option[String]
      def language: Option[Language]
    }

    class PersonImpl(val name: Option[String], val language: Option[Language]) extends Person

    val ctx = Map("p" -> new PersonImpl(Some("Philipp"), Some(Languages.DE)))

    eval("p.name", ctx) should be(ValNumber("Philipp"))

    // this is probably too far from the standard, but it could work if we could provide a custom context
    eval("p.language", ctx) should be(Val???(Languages.DE))
    eval("p.language = Language.DE", ctx) should be(ValBoolean(true))
    eval("p.language = null", ctx) should be(ValBoolean(false))

    // that would be OK as well
    eval("p.language", ctx) should be(ValString(Languages.DE.id))
    eval(""" p.language = "DE" """, ctx) should be(ValBoolean(true))
    eval("p.language = null", ctx) should be(ValBoolean(false))
  }
```

A more lightweight option for enums (than a full-fledged context provider) could be a CustomFeelValue SPI interface, which would allow to map an enum value (any value) to its string representation.
Something like
```
trait CustomFeelValue {
  def value: String
}
```
which domain objects would then need to implement.

**Comment by hannes-o-brunner** [comment]
As to the usage: We are looking to build some kind of "rule engine" for a domain where the individual rules for a given decision have very differing match criteria + necessary function calls. So a DMN implementation would be too clumsy, since the matrix would be quite sparsly populated and have to over-/misuse context.
Thats is why we are currently looking one level below DMN to directly embed an expression language and build a "rule engine" on top of it.

**Comment by hannes-o-brunner** [comment]
After thinking some more about this, we can probably split this issue into 2 parts:

1. support Scala Option properties
2. better enumeration support, maybe thinking along the lines of the [DMN 2.0 wishlist of Jan Purchase](http://blog.luxmagi.com/2016/04/our-dmn-2-0-wish-list-i-decision-logic/) in "Glossary - Robust handling of enumerations" (whose solution might be one of the tactical solutions above, maybe something different)

**Comment by saig0** [comment]
@hannes-o-brunner , I agree with you. I created additional issues for option #9  and enumeration #10 .

Since this kind of Scala enum is very specific, I think about to add a SPI for custom `ContextProvider` and / or `ValueMapper` . This give us full flexibility and make it easy to extend. 

=== 

Thank you for sharing your use case. It's sounds interessting =)

**Comment by saig0** [comment]
Update: I implemented #9 and #10.

I think we should make it possible to replace the default `ValueMapper` by a custom one. This allows you to map the sealed-trait-enum to `ValString`. 

```
trait ValueMapper {
  def toVal(x: Any): Val
  def unpackVal(x: Val): Any
}

class DefaultValueMapper implements ValueMapper {
  // current implementation
}

class FeelEngine(functionProvider: FunctionProvider = EmptyFunctionProvider, valueMapper: ValueMapper = new DefaultValueMapper) {
  // create a new context with the given value mapper
}
```

Also, I can build a more Java-like `ValueMapper` for Camunda DMN engine which maps list and context to Java Collections. 

@hannes-o-brunner , what do you think? Do you want to provide a PR?

**Comment by hannes-o-brunner** [comment]
Good, I'll come up with a proposal

**Comment by hannes-o-brunner** [comment]
Submitted [PR](https://github.com/camunda/feel-scala/pull/12)

**Comment by saig0** [comment]
Merged! Well done 👍
