### ISSUE TITLE
Double quotes in string literal are escaped

### ISSUE THREAD

**Issue by StrekoZ** [camunda/feel-scala#778]
**Describe the bug**
When trying to add a quote inside string `\"`, it's got replaced to `\\\"`

**To Reproduce**
Execute in FEEL playground 
`string length("\"") - string length(x)`
with a context
`{
  "x": "\""
}`
<img src="https://github.com/camunda/feel-scala/assets/5629819/b285db2c-5bd3-4c56-8d7c-1c3aeac241cc" height="300">

**Expected behavior**
Expected that length for both strings is equal (difference is 0)

**Environment**
* FEEL engine version: [1.17]
* Same is when using **feel-scala** dependency in a project
* Connector with Camunda `8.3.4`: https://github.com/camunda/connectors/issues/1432

**Comment by StrekoZ** [comment]
This place seems suspicious: https://github.com/camunda/feel-scala/pull/763/files#r1428154128
However issue also is reproducable in older version of FEEL Playgound: https://camunda.github.io/feel-scala/docs/playground/ (1.16 and 1.15 as well)

**Comment by saig0** [comment]
@StrekoZ thank you for reporting. :+1:
