### ISSUE TITLE
I can not access a list element with dynamic index

### ISSUE THREAD

**Issue by saig0** [camunda/feel-scala#80]
**Describe the bug**
It is not possible to access a list element (i.e. via filter expression) if the index is a variable reference instead of a constant number.

```js
["a","b","c"][2]
// "b"

["a","b","c"][index]
// failure: expected Boolean but found 'ValNumber(2)'
```

**To Reproduce**
1. Evaluate a filter expression `["a","b","c"][index]` with context variable `index` = `2`

**Expected behavior**
I can access a list element statically and dynamically with a variable reference in the same way.

**Environment**
Which version do you use? 1.10.0

**Comment by falko** [comment]
@saig0 Should this become a TCK test?

**Comment by saig0** [comment]
I didn't check the newest TCK tests yet. But it would make sense to have also test with non-static values :)
