### ISSUE TITLE
I can't interrupt an expression evaluation

### ISSUE THREAD

**Issue by vicmosin** [camunda/feel-scala#823]
**Is your feature request related to a problem? Please describe.**
The feel engine is currently stuck while executing long-running expressions because of the lack of "cooperation mode" ([ref](https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html)). It is not possible to interrupt the execution from outside the engine. 

Related forum discussion: https://forum.camunda.io/t/feelengines-cooperation-mode-while-performing-longrunning-and-resource-consuming-operations/51049

> We are using org.camunda.feel.FeelEngine instance to evaluate FEEL expressions and trying to find a proper way to “sandbox” this operation and give a dedicated timeout for each one, in case the user tries to execute a malicious expression.
We’ve came across the following expression as an example of such harmful snippet which can bring the instance down:
>
> count(for x in 1..(2 ** 16) return {"power": 2 ** x}) > 0

**Describe the solution you'd like**
The most classical solution is to repeatedly check whether the current thread was interrupted and throw an appropriate exception

**Comment by saig0** [comment]
@vicmosin thank you for raising this. :+1: I adjusted the issue description based on the forum discussion. 

I think this feature could be a small but useful improvement.

**Comment by entangled90** [comment]
I noticed that it's not possible to interrupt the engine if it doesn't hit an `eval` for too much. This happend when I was testing my fixes by using large lists. 
I think we need to add more checks even internally.
- if there's a single loop and it's size is big, we might check it once ever `n` operation (think like `10k`)
- If there's more than one loop, we can check it once every inner loop has ended

**Comment by saig0** [comment]
> complexity explosion caused by cross-joins

This was addressed with https://github.com/camunda/feel-scala/pull/1013. 

🏗️ I will plan to build a new patch release in the next few weeks.
