### ISSUE TITLE
Incorrect escaping in strings

### ISSUE THREAD

**Issue by StrekoZ** [camunda/feel-scala#879]
**Describe the bug**
Incorrect escping of backslash

**To Reproduce**
1. Open playground: https://camunda.github.io/feel-scala/docs/playground/
2. Use expression `x = "\\"`
3. Use  context `{ "x": "\\" }`

**Observed behavior**
![image](https://github.com/user-attachments/assets/0c20e18b-0214-4a0a-9679-6e1631bf2002)

**Expected behavior**
Output should be **true**

**Notes**
If expression is `x`, then in output there is string with 2 slashes instead of one
If expression is `"\\"` then currently output is string with 4 slashes, which is very srange

**Environment**
* FEEL engine version: [1.17]

**Comment by StrekoZ** [comment]
Similar problem described at: https://github.com/camunda/feel-scala/issues/778 (slightly different use case, but also related to backslash and escaping)

**Comment by saig0** [comment]
@StrekoZ thank you for reporting. :+1:
