### ISSUE TITLE
Extending variable naming convention

### ISSUE THREAD

**Issue by vicmosin** [camunda/feel-scala#884]
**Is your feature request related to a problem? Please describe.**
Historically one of our project's scripting engine supports the variables, written with kebab-case. Though the [specs](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-variables/) doesn't allow this , we found 2 different implementations: the [playground](https://camunda.github.io/feel-scala/docs/playground/?expression=MyArIHgtYQ%3D%3D&context=ewogICJ4LWEiOiA1Cn0%3D&expression-type=expression), provided by camunda doesn't support it, while at this [version](https://nikku.github.io/feel-playground/?e=3+%2B+x-a&c=%7B%0A++%22x-a%22%3A+5%0A%7D&t=expression&st=true) it works without any issue.

**Describe the solution you'd like**
My idea is to allow kebab-cased variables be supported by feel-scala engine implementation.

Would you be interested in such change? Though I didn't check the code yet and don't know how much effort is this

**Comment by saig0** [comment]
@vicmosin thank you for raising it. :+1: 

In the DMN spec, variable names can contain dashes `-` (, whitespace, and more). The current limitation is based on the parsing of the FEEL expression. If a dash can be part of a variable name, an expression may be ambiguous.

**Comment by vicmosin** [comment]
Yeah, this looks like a breaking change, so basically it's "no" to the suggestion?

**Comment by vicmosin** [comment]
@saig0 do you think something like this might be a solution for such variables?
 https://nikku.github.io/feel-playground/?e=3+%2B+%60x-a%60+%2B+z.%60a-b%60&c=%7B%0A++%22x-a%22%3A+5%2C%0A++%22z%22%3A+%7B%0A++++%22a-b%22%3A+5%0A++%7D%0A%7D&t=expression&st=true
