### ISSUE TITLE
Public API must contain all classes/objects/traits which are exposed in other public APIs

### ISSUE THREAD

**Issue by menski** [camunda/feel-scala#91]
Currently the Public API exposes classes/objects/traits from `impl` packages, for example `Context` https://github.com/camunda/feel-scala/blob/9760122317f34e184503ef9b534bda5a211fcff5/feel-engine/src/main/scala/org/camunda/feel/FeelEngine.scala#L97

This should be aligned so that no `impl` classes/objects/traits are exposed.

**Comment by tasso94** [comment]
Fixed with #94
