### ISSUE TITLE
CI for different JDK vendors

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/feel-scala#97]
**Is your feature request related to a problem? Please describe.**

* Needed by the Camunda Runtime team because we support more than OracleJDK

**Describe the solution you'd like**

* Have Jenkins jobs that run the builds with different JDKs, in particular IBM JDK and OpenJDK

**Comment by saig0** [comment]
@tasso94, do you want to work on this? You know the supported environments better than me ;)

**Comment by ThorbenLindhauer** [comment]
Closing this ticket. The coverage via the dmn-engine suite in the platform is good enough for us right now.
