### ISSUE TITLE
Use gitflow for this project

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/feel-scala#98]
**Is your feature request related to a problem? Please describe.**

* That way we don't have to interrupt development during releases

**Describe the solution you'd like**

* The workflow should be documented in the contributor's guide so that a developer can easily understand how it works and follow it
* The Camunda Runtime team in particular should be informed, because they currently do not work with gitflow for any other projects

**Comment by saig0** [comment]
Currently, I don't see a need for this because the contributions are not so often.
